eureka:
  instance:
    prefer-ip-address: true
  client:
    eureka-server-connect-timeout-seconds: 10
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
